const DEFAULT_COUNT_USERS = 5;
const BD_TABLE_USERS = 'Users';
const BD_TABLE_BOARDS = 'Boards';
const BD_TABLE_TASKS = 'Tasks';

const STATUS_CODE = {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
}

module.exports = {
    DEFAULT_COUNT_USERS,
    BD_TABLE_USERS,
    BD_TABLE_BOARDS,
    BD_TABLE_TASKS,
    STATUS_CODE,
}
